// examples/setup/lit-html/src/index.js
import flyd from "flyd"
import merge from "mergerino"
import { render } from "lit"

import { app, App } from "./app"

// Only for using Meiosis Tracer in development.
import meiosisTracer from "meiosis-tracer"

const update = flyd.stream()
const states = flyd.scan(merge, app.Initial(), update)

// Only for using Meiosis Tracer in development.
meiosisTracer({ selector: "#tracer", rows: 25, streams: [states] })

const actions = app.Actions(update)
const element = document.getElementById("app")
states.map(state => render(App({ state, actions }), element))

// examples/setup/react/src/index.js
import { render } from 'react-dom';
import flyd from 'flyd';

import { app } from './app';

const update = flyd.stream();
const states = flyd.scan((state, patch) => patch(state), app.initial, update);
const createCell = (state) => ({ state, update });
const cells = states.map(createCell);

// vv Only for using Meiosis Tracer in development.
import meiosisTracer from 'meiosis-tracer';
meiosisTracer({ selector: '#tracer', rows: 25, streams: [states] });
// ^^ Only for using Meiosis Tracer in development.

const element = document.getElementById('app');
cells.map((cell) => {
  render(app.view(cell), element);
});
