// examples/setup/lit-html/src/temperature/index.js
import { html } from "lit-html"

import { initialState } from "./initialState"
import { actions } from "./actions"

export const temperature = {
  initialState,
  actions
}

export const Temperature = ({ local }) => html`
  <div>
    <div style="margin-top: 0.8rem">
      ${local.state.label} Temperature: ${local.state.value}&deg;${local.state.units}
    </div>
    <div style="margin-top: 0.8rem">
      <button
        class="btn btn-primary"
        @click=${() => local.update(actions.increment(1))}
        style="margin-right: 0.4rem"
      >
        Increment
      </button>
      <button
        class="btn btn-primary"
        @click=${() => local.update(actions.increment(-1))}
        style="margin-right: 0.4rem"
      >
        Decrement
      </button>
      <button class="btn btn-default" @click=${() => local.update(actions.changeUnits())}>
        Change Units
      </button>
    </div>
  </div>
`

// examples/setup/react/src/temperature/index.jsx
import React, { Component } from "react"
import Button from "@material-ui/core/Button"

import { initialState } from "./initialState"
import { actions } from "./actions"

export const temperature = {
  initialState,
  actions
}

export class Temperature extends Component {
  render() {
    const { local } = this.props

    return (
      <div>
        <div style={{ marginTop: "0.8rem" }}>
          <label>
            {local.state.label} Temperature: {local.state.value}&deg;{local.state.units}
          </label>
        </div>
        <div style={{ marginTop: "0.8rem" }}>
          <Button
            variant="contained"
            onClick={() => local.update(actions.increment(1))}
            color="primary"
            style={{ marginRight: "0.4rem" }}
          >
            Increment
          </Button>
          <Button
            variant="contained"
            onClick={() => local.update(actions.increment(-1))}
            color="primary"
            style={{ marginRight: "0.4rem" }}
          >
            Decrement
          </Button>
          <Button
            variant="contained"
            onClick={() => local.update(actions.changeUnits())}
            color="secondary"
          >
            Change Units
          </Button>
        </div>
      </div>
    )
  }
}
