// examples/custom-elements/lit-element/src/app/index.js
import { LitElement, html } from "lit-element"

import { conditions, Conditions } from "../conditions"
import { dateTime, DateTime } from "../dateTime"
import { temperature, Temperature } from "../temperature"
import { bootstrap } from "../util"

export const app = {
  Initial: () => ({
    dateTime: dateTime.Initial(),
    conditions: conditions.Initial(),
    "temperature:air": temperature.Initial(),
    "temperature:water": temperature.Initial()
  }),

  Actions: update =>
    Object.assign(
      {},
      conditions.Actions(update),
      dateTime.Actions(update),
      temperature.Actions(update)
    )
}

export const App = ({ initial, actions }) =>
  class extends LitElement {
    static get properties() {
      return {
        state: Object,
        actions: Object
      }
    }
    constructor() {
      super()
      this.state = initial
    }
    render() {
      const { state } = this
      return html`
        ${bootstrap}
        <div class="row">
          <div class="col-md-4">
            <date-time .state=${state} id="dateTime" .actions=${actions}></date-time>
          </div>
          <div class="col-md-4">
            <sky-conditions .state=${state} id="conditions" .actions=${actions}></sky-conditions>
            <temp-el .state=${state} id="temperature:air" .actions=${actions}></temp-el>
            <temp-el .state=${state} id="temperature:water" .actions=${actions}></temp-el>
          </div>
        </div>
      `
    }
  }

customElements.define("sky-conditions", Conditions)
customElements.define("date-time", DateTime)
customElements.define("temp-el", Temperature)

// examples/setup/react/src/app/index.jsx
import React, { Component } from "react"

import { conditions, Conditions } from "../conditions"
import { dateTime, DateTime } from "../dateTime"
import { temperature, Temperature } from "../temperature"

export const app = {
  initialState: () => Object.assign({},
    dateTime.initialState(),
    conditions.initialState(),
    { air: temperature.initialState("Air") },
    { water: temperature.initialState("Air") }
  ),
  actions: update => Object.assign({},
    dateTime.actions(update),
    conditions.actions(update),
    temperature.actions(update)
  )
}

export class App extends Component {
  constructor(props) {
    super(props)
    this.state = props.states()
  }

  componentDidMount() {
    this.props.states.map(state => {
      this.setState(state)
    })
  }

  render() {
    const state = this.state
    const { actions } = this.props

    return (
      <div>
        <DateTime state={state} actions={actions} />
        <Conditions state={state} actions={actions} />
        <Temperature state={state} id="air" actions={actions} />
        <Temperature state={state} id="water" actions={actions} />
      </div>
    )
  }
}
