// examples/custom-elements/lit-element/src/index.js
import flyd from "flyd"
import merge from "mergerino"

import { app, App } from "./app"

// Only for using Meiosis Tracer in development.
import meiosisTracer from "meiosis-tracer"

const update = flyd.stream()
const states = flyd.scan(merge, app.Initial(), update)

// Only for using Meiosis Tracer in development.
meiosisTracer({ selector: "#tracer", rows: 25, streams: [states] })

const actions = app.Actions(update)
customElements.define("meiosis-app", App({ initial: app.initial, actions }))
const element = document.createElement("meiosis-app")
document.getElementById("app").append(element)

states.map(state => {
  element.state = state
})

// examples/setup/preact/src/index.jsx
import { h, render } from "preact"
import flyd from "flyd"

import { app, App } from "./app"

// Only for using Meiosis Tracer in development.
import meiosisTracer from "meiosis-tracer"

const update = flyd.stream()
const states = flyd.scan((state, patch) => patch(state), app.initial, update)

// Only for using Meiosis Tracer in development.
meiosisTracer({ selector: "#tracer", rows: 25, streams: [states] })

const actions = app.Actions(update)
render(<App states={states} actions={actions} />, document.getElementById("app"))
