// examples/setup/lit-html/src/app/index.js
import { html } from "lit-html"

import { conditions, Conditions } from "../conditions"
import { dateTime, DateTime } from "../dateTime"
import { temperature, Temperature } from "../temperature"

export const app = {
  initialState: () => Object.assign({},
    dateTime.initialState(),
    conditions.initialState(),
    { air: temperature.initialState("Air") },
    { water: temperature.initialState("Air") }
  ),
  actions: update => Object.assign({},
    dateTime.actions(update),
    conditions.actions(update),
    temperature.actions(update)
  )
}

export const App = (state, actions) => html`
  <div class="row">
    <div class="col-md-4">
      ${DateTime(state, actions)}
    </div>
    <div class="col-md-4">
      ${Conditions(state, actions)}
      ${Temperature(state, "air", actions)}
      ${Temperature(state, "water", actions)}
    </div>
  </div>
`

// examples/setup/preact/src/app/index.jsx
import { h, Component } from "preact"

import { conditions, Conditions } from "../conditions"
import { dateTime, DateTime } from "../dateTime"
import { temperature, Temperature } from "../temperature"

export const app = {
  initialState: () => Object.assign({},
    dateTime.initialState(),
    conditions.initialState(),
    { air: temperature.initialState("Air") },
    { water: temperature.initialState("Air") }
  ),
  actions: update => Object.assign({},
    dateTime.actions(update),
    conditions.actions(update),
    temperature.actions(update)
  )
}

export class App extends Component {
  componentWillMount() {
    this.props.states.map(state => {
      this.setState(state)
    })
  }

  render() {
    const state = this.state
    const { actions } = this.props

    return (
      <div>
        <DateTime state={state} actions={actions} />
        <Conditions state={state} actions={actions} />
        <Temperature state={state} id="air" actions={actions} />
        <Temperature state={state} id="water" actions={actions} />
      </div>
    )
  }
}
